server/apps/ad/urls.py
from django.conf.urls import patterns, url
from haystack.query import SearchQuerySet

from .views import DetailAdView, AdFacetedSearchView
from .forms import AdSearchForm

sqs = SearchQuerySet().facet('categories').facet('localities').facet('provinces')

urlpatterns = patterns('',
                       # List and Search ads with facets
                       url(r'^search/$',
                           AdFacetedSearchView(form_class=AdSearchForm,
                                               searchqueryset=sqs,
                                               template='ad/list.html'),
                           name='search-facet'),

                       # Detail Ad
                       url(r'^(?P<slug>[a-zA-Z0-9_.-]+)/$',
                           DetailAdView.as_view(),
                           name="detail"),

                        )

server/apps/user/urls.py
from django.conf.urls import patterns, url

from .views import LogoutView

urlpatterns = patterns('',
                       url(r'^logout/$',
                           LogoutView.as_view(),
                           name='my-logout'),
                       )

server/compraloahi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from apps.favorite.views import HasFavoriteNearApiView

from apps.userProfile.views import StoreView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HomeView, DashBoardView, log, send_notification, TermAndConditionView
from django.views.generic import TemplateView
from django.conf import settings
from apps.util.views import RegisterInterested, TemplateMessage, ContactFormView

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view()),

    url(r'^report-error/$', 'apps.report_error.views.report_error', name='report-error'),

    url('^interested/$', RegisterInterested.as_view(), name='interested-app'),
    url('^dynamic-message/$', TemplateMessage.as_view(), name='dynamic-message'),
    url(r'^face/$', 'apps.util.views.register_count_whered', {'whered': 'facebook'}),
    url(r'^info/$', 'apps.util.views.register_count_whered', {'whered': 'folleto1'}),
    url(r'^contactenos/$', ContactFormView.as_view(), name='contact'),

    # TODO : This url belong to api
    url(r'^favorites/near/$', HasFavoriteNearApiView.as_view() , name='favorite-near'),

    url(r'^oportunidades-anunciante/$', TemplateView.as_view(template_name='oportunidades-anunciante.html')),

    url(r'^oportunidades-interesado/$', TemplateView.as_view(template_name='oportunidades-interesado.html')),

    url('^faq/', include('apps.faq.urls', namespace='faq')),

    url('^terminosycondiciones/(?P<template>.*)$', TermAndConditionView.as_view(), name='termsandcondition'),

    # Terms and Conditions
    #url(r'^terms/', include('termsandconditions.urls')),

    # Include API
    (r'^api/v1/', include('compraloahi.urls_api', namespace='api')),

    url(r'^favorite/' , include('apps.favorite.urls', namespace='favorite')),

    # URL load dashboard
    url(r'^panel/.*$', DashBoardView.as_view(), name='dashboard'),

    # Admin django
    url(r'^admin/', include(admin.site.urls)),

    # My apps Ad
    url(r'^item/', include("apps.ad.urls", namespace="ad")),

    url(r'^grupos/', include("apps.interest_group.urls", namespace="group")),

    # My apps User
    (r'^users/',
     include('apps.user.urls',
             namespace='my-user')),

    url(r'^calification/', include('apps.rating.urls', namespace="rating")),

    # App Allauth (social authentication)
    (r'^accounts/', include('allauth.urls')),

    # Parche comments
    (r'^comments/post/$',
     'compraloahi.views.comment_post_wrapper'),

    # Package comments
    (r'^comments/', include('django_comments_xtd.urls')),

    url(r'^tienda/(?P<slug>[a-zA-Z0-9_.-]+)/$',
        StoreView.as_view(),
        name="store"),

                       )

if settings.DEBUG:
    urlpatterns =  patterns('',
                      url(r'^send_notification/', send_notification),
                      url(r'^log/', log),
                      url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                      ) + staticfiles_urlpatterns() + urlpatterns

server/compraloahi/views.py
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django_comments.views.comments import post_comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User

from rest_framework import pagination

from push_notifications.models import GCMDevice
from django.views.decorators.csrf import csrf_exempt

from apps.ad.models import Ad
from apps.user.serializers import UserAuthenticationSerializer
from apps.util.forms import RegisterInterestedForm


import logging

logger = logging.getLogger('debug')

@csrf_exempt
def log(request):
    logger.debug( request.body )
    return HttpResponse( "algo" )


# Test send notification to android
def send_notification(request):
    device = GCMDevice.objects.first()

    device.send_message(request.GET.get('msg', "Hola"))

    return HttpResponse("Notificacion enviada con exito")


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        cxt = super(HomeView, self).get_context_data(*args, **kwargs)
        cxt['form'] = RegisterInterestedForm()
        return cxt

    #def dispatch(self, request, *args, **kwargs):
    #    return redirect('/item/search/?q=')

class TermAndConditionView(TemplateView):
    template_name = 'termcondition/index.html'

    def get_template_names(self):
        if self.kwargs.get('template'):
            return 'termcondition/%s.html' %(self.kwargs['template'])
        else:
            return super(TermAndConditionView, self).get_template_names()

class DashBoardView(TemplateView):
    """
        View to init dashboard
    """
    template_name = 'dashboard/base.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DashBoardView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DashBoardView, self).get_context_data(**kwargs)

        context['user_data'] = UserAuthenticationSerializer(instance=self.request.user).data
        return context


def comment_post_wrapper(request):
    if request.user.is_authenticated():
        # In case of a reply, check that the user is answering a comment of his own ad
        object_pk = request.POST.get('object_pk', '')
        if int( request.POST.get('reply_to', 0) ) > 0:
            if ( Ad.objects.get(pk=object_pk).author == request.user):
                return post_comment(request) # VER SI ESTE ES EL POST, o EL DE COMMENT XTD
        else:
            if ( Ad.objects.get(pk=object_pk).author != request.user):
                return post_comment(request) # VER SI ESTE ES EL POST, o EL DE COMMENT XTD

    return HttpResponse('Unauthorized', status=401)


# Generates Auth Tokens for all Users
class GenerateAllAuthToken(APIView):
    def get(self, request):
        response = "{"
        for user in User.objects.all():
            token, created = Token.objects.get_or_create(user=user)
            response += "{" + "username:" + user.username + ",pk: " + str(user.pk) + ",token:" + token.key + "},"
        response += "}"
        return Response(response)

generate_all_auth_token = GenerateAllAuthToken.as_view()


class CustomPagination(pagination.PageNumberPagination):
    page_size = 200
    page_size_query_param = 'page'
    max_page_size = 200
    """
        Custom pagination
            return only page number in next and previous pages.
    """
    def get_paginated_response(self, data):
        resp = {}
        resp['next'] = self.page.next_page_number() if self.page.has_next() else None
        resp['previous'] = self.page.previous_page_number() if self.page.has_previous() else None
        resp['count'] = self.page.paginator.count
        resp['results'] = data
        return Response(resp)

server/compraloahi/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <!-- Title -->
    <title> {% block title %} Compraloahí {% endblock %}</title>

    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta charset="UTF-8">

    <link rel="icon" type="image/png" href="/static/image/compraloahi-iso-logo-icon.png">

    {% include 'layout/stylesheets.html' %}
    {% block css_header_block %}
        <link rel="stylesheet" href="/static/css/less/base.css"/>
    {% endblock %}


    <!-- JQUERY -->
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>

  <!--  <script src="/static/assets/plugins/3d-bold-navigation/js/modernizr.js"></script>-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="page-header-fixed" {% block angular_app_declare_block %}{% endblock %}>
<div class="overlay"></div>

{% block search_nav %}
<form class="search-form" action="{% url 'ad:search-facet' %}" method="GET">
    <div class="input-group">
        <input type="text" name="q" class="search-input" placeholder="Busca productos y servicio cerca.">
                <span class="input-group-btn">
                    <button class="btn btn-default icon-search" type="submit"><i class="fa fa-search"></i></button>
                </span>
    </div><!-- Input Group -->
</form><!-- Search Form -->
{% endblock %}



<main class="page-content content-wrap">

    {% include 'layout/navigation.html' %}


    <div class="page-inner" style="min-height: 100%;">
        <div class="container-scroll">
            {% block body_block %}
            <!-- CONTENT -->
            {% endblock %}
            {% include 'layout/report.html' %}
            {% block footer %}
                {% include 'layout/footer.html' %}
            {% endblock %}
        </div>
    </div><!-- Page Inner -->
</main><!-- Page Content -->
<div class="cd-overlay"></div>

<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>

{% include 'layout/javascripts.html' %}

{% block js_footer_block %}{% endblock %}

</body>
</html>

server/compraloahi/templates/layout/contact.html
<a href="#" id="modal-contact">Contactenos</a>
<div class="modal fade" tabindex="-1" id="modalContact" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Contactenos</h4>
            </div>
            <div class="modal-body" id="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" id="btn-submit-contact">Enviar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
    window.onload = function() {
        $("#modal-contact").click(function(){
            $("#modalContact").modal('show');
            $.ajax({
                url: "/contactenos/",
                type: 'GET',
                success: function(response) {
                    $("#modalContact").find('#modal-body').html(response);
                }
            });
        });


        $('#btn-submit-contact').click(function(){
            $.ajax({
                url: "/contactenos/",
                type: 'POST',
                data: $("#modalContact").find('#modal-body').find('form').serialize(),
                beforeSend: function(xhr, settings){
                    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                        // Only send the token to relative URLs i.e. locally.
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    }
                },
                success: function(response) {
                    $("#modalContact").find('#modal-body').html(response);
                    $('#btn-submit-contact').css('display', 'none');
                }
            });
        });
    };


</script>

server/compraloahi/templates/layout/footer.html
<div class="page-footer">
    <div class="container">
        <p class="no-s">2016 &copy; Compraloahi hecho por <a href="http://www.context.com.ar" target="_blank">Context</a>   |
            <a href="{% url 'termsandcondition' 'terms' %}">Terminos y condiciones</a> | <a href="{% url 'termsandcondition' 'privacity' %}">Politicas de privacidad</a> | <a
                    href="/faq/">Ayuda</a> | {% include 'layout/contact.html' %}
        </p>
    </div>
</div>

server/compraloahi/templates/layout/javascripts.html
{% load staticfiles %}

<script src="{% static 'bower_components/pace-master/pace.min.js' %}"></script>
<!-- STYLE SCROLL JQUERY-->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>

<script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/theme/theme.js' %}"></script>

<script type="text/javascript" src="{% static 'bower_components/toastr/toastr.js' %}"></script>


<script>
    toastr.options = {
      "closeButton": true,
      "debug": false,
      "newestOnTop": false,
      "progressBar": true,
      "positionClass": "toast-bottom-left",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    };
    {% if messages %}
        {% for message in messages %}
            {% if message.tags and message.tags == 'success' %}
                toastr.success('{{ message }}');
            {% elif message.tags and message.tags == 'warning' %}
                toastr.warning('{{ message }}');
            {% elif message.tags and message.tags == 'error' %}
                toastr.error('{{ message }}');
            {% else %}
                toastr.info('{{ message }}');
            {% endif %}
        {% endfor %}
    {% endif %}

</script>

server/compraloahi/templates/layout/navigation.html
<div class="navbar">
    <div class="navbar-inner container-fluid">
        <div class="sidebar-pusher">
            <a class="" href="/">
                <i><img  id="iso-logo" src="/static/image/compraloahi-iso-logo.png"/></i>
            </a>
        </div>
        <div class="logo-box">
            <a href="/" class="logo-text"><span><img  id="logo" src="/static/image/compraloahi-logo.png"/> </span></a>
        </div><!-- Logo Box -->
        <div class="nav-user-dropdown-responsive ">
            <a class="waves-effect waves-button waves-classic a">
            {% load msg_tags %}
                {% if user.is_authenticated %}

                    <div class="nav-user-dropdown-responsive dropdown">
                        <a href="#" class="a dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown">
                            <img class="img-circle avatar" src="{{ user.profile.image.url }}" width="40" height="40" alt="">
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-list" role="menu">
                            <li role="presentation"><a href="/panel/user/profile/"><i class="fa fa-user"></i>Perfil</a></li>
                            <li role="presentation"><a href="/panel/mensajes/inbox"><i class="fa fa-envelope"></i>Bandeja<span class="badge badge-success" style="position: absolute; right: 10px;">{% get_msgs_unread_count %}</span></a></li>
                            <li role="presentation"><a href="/panel/mis-avisos/"><i class="fa fa-bullhorn"></i> Mis Avisos</a></li>
                            <li role="presentation"><a href="/faq/"><i class="fa fa-question-circle"></i> Ayuda</a></li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation"><a href="{% url 'my-user:my-logout' %}"><i class="fa fa-sign-out m-r-xs"></i>Salir</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="nav-user-dropdown-responsive">
                        <div class="a">
                            <div class="nav-user-dropdown-responsive">
                                <a href="/accounts/login/">Entra</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </a>
        </div>
        <div class="topmenu-outer">
            <div class="top-menu">
                <ul class="nav navbar-nav navbar-right">
                    <!--<li>
                        <a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i class="fa fa-search"></i></a>
                    </li>-->

                    {% if user.is_authenticated %}

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="badge badge-success pull-right">{% get_msgs_unread_count %}</span></a>
                            <ul class="dropdown-menu title-caret dropdown-lg" role="menu">
                                <li><p class="drop-title">Tienes {% get_msgs_unread_count %} mensajes nuevos !</p></li>
                                <li class="dropdown-menu-list slimscroll messages">
                                    <ul class="list-unstyled">
                                        {% get_msgs_unread_list %}
                                        {% if msgs %}
                                            {% for msg in msgs %}
                                                 <li>
                                                    <a href="/panel/mensajes/hilo/{% if msg.thread %}{{ msg.thread.id }}{% else %}{{ msg.id }}{% endif %}">
                                                        <div class="msg-img"><div class="online off"></div><img class="img-circle" src="/static/image/img-default-profile.jpg" alt=""></div>
                                                        <p class="msg-name">{{ msg.sender }}</p>
                                                        <p class="msg-text">{{ msg.subject }}</p>
                                                        <p class="msg-time">{{ msg.sent_at }}</p>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </li>
                                <li class="drop-all"><a href="/panel/mensajes/inbox" class="text-center">Todos los mensajes</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            {% load notification_tags %}
                            <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown"><i class="fa fa-bell"></i><span class="badge badge-success pull-right">{% get_notifications_unread_count %}</span></a>
                            <ul class="dropdown-menu title-caret dropdown-lg" role="menu">
                                <li><p class="drop-title">Tienes {% get_notifications_unread_count %} notificaciones nuevas !</p></li>
                                <li class="dropdown-menu-list slimscroll tasks">
                                    <ul class="list-unstyled">
                                        {% get_notificacions_unread_list %}
                                        {% if notifications %}
                                            {% for notification in notifications %}
                                                 <li>
                                                    <a href="{{ notification.get_url }}">
                                                        <div class="task-icon badge badge-success">
                                                            <i class="fa
                                                            {% if notification.type == 'cmmt' %}
                                                                fa-comment
                                                            {% elif notification.type == 'msg' %}
                                                                fa-inbox
                                                            {% elif notification.type == 'fav' %}
                                                                fa-heart
                                                            {% elif notification.type == 'cal' %}
                                                                fa-bus
                                                            {% else %}
                                                                fa-bell
                                                            {% endif %}
                                                            "></i>
                                                        </div>
                                                        <span class="badge badge-roundless badge-default pull-right">{{ notification.created }}</span>
                                                        <p class="task-details">{{ notification.message }}</p>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </li>
                                <li class="drop-all"><a href="#" class="text-center">Todas las notificaciones</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" data-toggle="dropdown">
                                <span class="user-name">{{ user.username }}<i class="fa fa-angle-down"></i></span>
                                <img class="img-circle avatar" src="{{ user.profile.image.url }}" width="40" height="40" alt="">
                            </a>
                            <ul class="dropdown-menu dropdown-list" role="menu">
                                <li role="presentation"><a href="/panel/user/profile/"><i class="fa fa-user"></i>Perfil</a></li>
                                <li role="presentation"><a href="/panel/mensajes/inbox"><i class="fa fa-envelope"></i>Bandeja<span class="badge badge-success" style="position: absolute; right: 10px;" >{% get_msgs_unread_count %}</span></a></li>
                                <li role="presentation"><a href="/panel/mis-avisos/"><i class="fa fa-bullhorn"></i> Mis Avisos</a></li>
                                <li role="presentation"><a href="/faq/"><i class="fa fa-question-circle"></i> Ayuda</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation"><a href="{% url 'my-user:my-logout' %}"><i class="fa fa-sign-out m-r-xs"></i>Salir</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/accounts/signup/" ><button class="btn btn-warning" style="margin-top: -5px; color: black;">Registrate</button></a></li>
                            <li><a href="/accounts/login/">Entra</a></li>
                            <li><a href="/faq/"><i class="fa fa-question-circle"></i></a></li>
                        </ul>
                    {% endif %}

                </ul><!-- Nav -->
            </div><!-- Top Menu -->
        </div>
    </div>
</div><!-- Navbar -->

server/compraloahi/templates/layout/report.html
{#<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">#}
<div class="feedback left">
    <div class="tooltips">
        <div class="btn-group dropup">
            <button type="button" class="btn btn-danger dropdown-toggle btn-circle btn-lg" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bug fa-2x" title="Report Bug"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-right dropdown-menu-form">
                <li>
                    <div class="report">
                        <h2 class="text-center">Reportar error o sugerencia</h2>
                        <form class="doo" method="post" action="/report-error/" enctype="multipart/form-data">
                            <div class="col-sm-12">
                                <textarea required name="comment" class="form-control" placeholder="Por favor, díganos lo que fallo o problema que ha encontrado, proporcione tantos detalles como sea posible. O alguna suguerencia para cambiar. Si precionas sobre el icono de camara, nos enviará una foto de la pagina, esto nos facilitara entender el fallo o suguerencia."></textarea>
                                <input name="screenshot" type="hidden" class="screen-uri">
                                <span class="screenshot pull-right"><i class="fa fa-camera cam" title="Take Screenshot"></i></span>
                            </div>
                            <div class="col-sm-12 clearfix">
                                <button class="btn btn-success btn-block">Enviar Reporte</button>
                            </div>
                        </form>
                    </div>
                    <div class="loading text-center hideme">
                        <h2>Esperar por favor...</h2>
                        <h2><i class="fa fa-refresh fa-spin"></i></h2>
                    </div>
                    <div class="reported text-center hideme">
                        <h2>Muchas gracias!</h2>
                        <p>Su presentación ah sido recibido, lo revisaremos a la brevedad. <br/> Muchas gracias por su tiempo</p>
                        <div class="col-sm-12 clearfix">
                            <button class="btn btn-success btn-block do-close">Cerrar</button>
                        </div>
                    </div>
                    <div class="failed text-center hideme">
                        <h2>Oh no!</h2>
                        <p>Parece que su presentación no se ha enviado.<br><br><a href="mailto:soporte@compraloahi.com.ar">Trate de ponerse en contacto con nosotros por el método antiguo.</a></p>
                        <div class="col-sm-12 clearfix">
                            <button class="btn btn-danger btn-block do-close">Cerrar</button>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>


<style>
    .btn-circle.btn-lg {
        width: 40px;
        height: 40px;
        padding: 5px 8px;
        font-size: 12px;
        line-height: 1.33;
        border-radius: 25px;
    }

    .feedback{position: fixed;}

    .feedback textarea{height: 180px; }
    .feedback .screenshot{ position: relative; top: -24px; right: 10px; opacity: .6}
    .feedback .screenshot:hover{  opacity: 1}
    .feedback .reported p, .feedback .failed p  { height: 190px}


    .feedback.left{left:10px !important; bottom:10px !important; position: fixed; z-index: 100;}
    .feedback.right{right:5px; bottom:15px}

    .feedback .dropdown-menu{width: 290px;height: 320px;bottom: 50px;}
    .feedback.left .dropdown-menu{ left: 0px}
    .feedback.right .dropdown-menu{ right: 0px}
    .feedback .hideme{ display: none}
</style>

<script>
    (function ( $ ) {
        $.fn.feedback = function(success, fail) {
            self=$(this);
            self.find('.dropdown-menu-form').on('click', function(e){e.stopPropagation()})

            self.find('.screenshot').on('click', function(){
                self.find('.cam').removeClass('fa-camera fa-check').addClass('fa-refresh fa-spin');
                html2canvas($(document.body), {
                    onrendered: function(canvas) {
                        self.find('.screen-uri').val(canvas.toDataURL("image/png"));
                        self.find('.cam').removeClass('fa-refresh fa-spin').addClass('fa-check');
                    }
                });
            });

            self.find('.do-close').on('click', function(){
                self.find('.dropdown-toggle').dropdown('toggle');
                self.find('.reported, .failed').hide();
                self.find('.report').show();
                self.find('.cam').removeClass('fa-check').addClass('fa-camera');
                self.find('.screen-uri').val('');
                self.find('textarea').val('');
            });

            failed = function(){
                self.find('.loading').hide();
                self.find('.failed').show();
                if(fail) fail();
            }

            self.find('form').on('submit', function(){
                self.find('.report').hide();
                self.find('.loading').show();
                $.post( $(this).attr('action'), $(this).serialize(), null, 'json').done(function(res){
                    if(res.result == 'success'){
                        self.find('.loading').hide();
                        self.find('.reported').show();
                        if(success) success();
                    } else failed();
                }).fail(function(res){
                    {# TODO: Siempre entra por el fail, al reparar quitar el if else y dejar solo el metodo failed #}
                    if(res.status == 200){
                        self.find('.loading').hide();
                        self.find('.reported').show();
                        if(success) success();
                    }else{
                        failed();
                    }

                });
                return false;
            });
        };
    }( jQuery ));

    $(document).ready(function () {
        $('.feedback').feedback();
    });
</script>