server/apps/faq/urls.py
from __future__ import absolute_import

from django.conf.urls import *
from . import views

from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^faq/$',
        views.TopicList.as_view(),
        name='faq_topic_list'),
    url(r'^$',
        views.FaqIndexView.as_view(),
        name='faq_index'),
    url(r'^search/$',
        views.SearchView.as_view(),
        name='faq_search'),

    url(r'^questions/$',
        views.QuestionOverviewList.as_view(),
        name='faq_question_list',),

    url(r'^detail/(?P<topic_slug>[\w-]+)/(?P<slug>[\w-]+)/helpful/$',
        'apps.faq.views.question_help_full_vote',
        name='question_helpful'
    ),
    url(r'^submit/$',
        views.SubmitFAQ.as_view(),
        name='faq_submit',
    ),
    url(r'^submit/thanks/$',
        views.SubmitFAQThanks.as_view(),
        name='faq_submit_thanks',
    ),
    url(r'^(?P<slug>[\w-]+)/$',
        views.TopicDetail.as_view(),
        name='faq_topic_detail',
    ),
    # url(r'^(?P<topic_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
    #     views.QuestionDetail.as_view(),
    #     name='faq_question_detail',
    # ),
)

server/compraloahi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from apps.favorite.views import HasFavoriteNearApiView

from apps.userProfile.views import StoreView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HomeView, DashBoardView, log, send_notification, TermAndConditionView
from django.views.generic import TemplateView
from django.conf import settings
from apps.util.views import RegisterInterested, TemplateMessage, ContactFormView

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view()),

    url(r'^report-error/$', 'apps.report_error.views.report_error', name='report-error'),

    url('^interested/$', RegisterInterested.as_view(), name='interested-app'),
    url('^dynamic-message/$', TemplateMessage.as_view(), name='dynamic-message'),
    url(r'^face/$', 'apps.util.views.register_count_whered', {'whered': 'facebook'}),
    url(r'^info/$', 'apps.util.views.register_count_whered', {'whered': 'folleto1'}),
    url(r'^contactenos/$', ContactFormView.as_view(), name='contact'),

    # TODO : This url belong to api
    url(r'^favorites/near/$', HasFavoriteNearApiView.as_view() , name='favorite-near'),

    url(r'^oportunidades-anunciante/$', TemplateView.as_view(template_name='oportunidades-anunciante.html')),

    url(r'^oportunidades-interesado/$', TemplateView.as_view(template_name='oportunidades-interesado.html')),

    url('^faq/', include('apps.faq.urls', namespace='faq')),

    url('^terminosycondiciones/(?P<template>.*)$', TermAndConditionView.as_view(), name='termsandcondition'),

    # Terms and Conditions
    #url(r'^terms/', include('termsandconditions.urls')),

    # Include API
    (r'^api/v1/', include('compraloahi.urls_api', namespace='api')),

    url(r'^favorite/' , include('apps.favorite.urls', namespace='favorite')),

    # URL load dashboard
    url(r'^panel/.*$', DashBoardView.as_view(), name='dashboard'),

    # Admin django
    url(r'^admin/', include(admin.site.urls)),

    # My apps Ad
    url(r'^item/', include("apps.ad.urls", namespace="ad")),

    url(r'^grupos/', include("apps.interest_group.urls", namespace="group")),

    # My apps User
    (r'^users/',
     include('apps.user.urls',
             namespace='my-user')),

    url(r'^calification/', include('apps.rating.urls', namespace="rating")),

    # App Allauth (social authentication)
    (r'^accounts/', include('allauth.urls')),

    # Parche comments
    (r'^comments/post/$',
     'compraloahi.views.comment_post_wrapper'),

    # Package comments
    (r'^comments/', include('django_comments_xtd.urls')),

    url(r'^tienda/(?P<slug>[a-zA-Z0-9_.-]+)/$',
        StoreView.as_view(),
        name="store"),

                       )

if settings.DEBUG:
    urlpatterns =  patterns('',
                      url(r'^send_notification/', send_notification),
                      url(r'^log/', log),
                      url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                      ) + staticfiles_urlpatterns() + urlpatterns

server/apps/faq/forms.py
"""
Here we define a form for allowing site users to submit a potential FAQ that
they would like to see added.

From the user's perspective the question is not added automatically, but
actually it is, only it is added as inactive.
"""

from __future__ import absolute_import
import datetime
from django import forms
from .models import Question, Topic

class SubmitFAQForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['topic', 'text', 'answer']

server/apps/faq/views.py
from __future__ import absolute_import

from django.db.models import Max, Sum, Count
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.sites.models import Site
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _
from django.views.generic import View, ListView, DetailView, TemplateView, CreateView
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template.response import TemplateResponse

from .models import Question, Topic, QuestionScore
from .forms import SubmitFAQForm
from .utils import search

import json


# TODO: Crear mixins para poder llevar "topics" a todas las vistas

class FaqIndexView(ListView):
    model = Topic
    template_name = 'faq/index.html'
    allow_empty = True
    context_object_name = "topics"

    def get_context_data(self, **kwargs):
        data = super(FaqIndexView, self).get_context_data(**kwargs)

        last_updated = Question.objects.filter(status=1).order_by('updated_on')[:5]

        max_score = QuestionScore.objects.all().order_by('score')[:20].values_list('question')

        popular_questions = Question.objects.filter(id__in=max_score, status=1)

        try:
            topic = Topic.objects.get(slug='preguntas-frecuentes')
            common_question = topic.questions.filter(status=1)
        except Topic.DoesNotExist:
            common_question = []

        # TODO: popular questions divider two for frontend
        data.update({'last_updated': last_updated,
                     'popular_questions': popular_questions[:10],
                     'popular_questions2': popular_questions[10:],
                     'common_question': common_question
        })
        return data

    def get_queryset(self):
        return Topic.site_objects.filter().order_by('-sort_order')




class TopicList(ListView):
    model = Topic
    template_name = "faq/topic_list.html"
    allow_empty = True
    context_object_name = "topics"

    def get_context_data(self, **kwargs):
        data = super(TopicList, self).get_context_data(**kwargs)

        # This slightly magical queryset grabs the latest update date for
        # topic's questions, then the latest date for that whole group.
        # In other words, it's::
        #
        #   max(max(q.updated_on for q in topic.questions) for topic in topics)
        #
        # Except performed in the DB, so quite a bit more efficient.
        #
        # We can't just do Question.objects.all().aggregate(max('updated_on'))
        # because that'd prevent a subclass from changing the view's queryset
        # (or even model -- this view'll even work with a different model
        # as long as that model has a many-to-one to something called "questions"
        # with an "updated_on" field). So this magic is the price we pay for
        # being generic.

        last_updated = data['object_list'].annotate(updated=Max('questions__updated_on'))\
                                          .aggregate(Max('updated'))

        data.update({'last_updated': last_updated['updated__max']})

        return data

    def get_queryset(self):
        return Topic.site_objects.filter().order_by('-sort_order')


class TopicDetail(DetailView):
    model = Topic
    template_name = "faq/topic_detail.html"
    context_object_name = "topic"

    def get_object(self, queryset=None):
        topic = super(TopicDetail, self).get_object(queryset)
        topic.add_view()
        return topic

    def get_context_data(self, **kwargs):
        # Include a list of questions this user has access to. If the user is
        # logged in, this includes protected questions. Otherwise, not.
        qs = self.object.questions.active()
        if self.request.user.is_anonymous():
            qs = qs.exclude(protected=True)

        data = super(TopicDetail, self).get_context_data(**kwargs)
        data.update({
            'questions': qs,
            'topics': Topic.objects.all(),
        })
        return data


class QuestionOverviewList(ListView):
    model = Question
    template_name = "faq/question_list.html"
    allow_empty = True
    context_object_name = "questions"

    def get_context_data(self, **kwargs):
        return self.get_question_score(**kwargs)

    def get_question_score(self, **kwargs):
        data = super(QuestionOverviewList, self).get_context_data(**kwargs)
        questions = Question.site_objects.active().annotate(
            nb_positive=Sum('questionscore__score'),
            nb_all=Count('questionscore')
        ).order_by('-topic__nr_views')

        for question in questions:
            if question.nb_all > 0:
                percentage = (question.nb_positive or 0)*100.0 / question.nb_all
                question.score = percentage
            else:
                question.score = "NA"

        if kwargs.get('sort') == "score":
            questions = sorted(questions, key=(lambda question: question.score), reverse=True)

        data.update({'questions': questions, 'topics': Topic.objects.all()})
        return data

    def get_queryset(self):
        return Question.site_objects.all()


class QuestionDetail(DetailView):
    template_name = "faq/question_detail.html"

    def _allowed(self, question):
        """
        Allow authenticated admin users to preview a question

        :param question:
        :return:
        """
        if question.is_active() or ('preview' in self.request.GET and self.request.user.is_staff):
            return True

    def get_object(self, queryset=None):
        question = super(QuestionDetail, self).get_object(queryset)

        if self._allowed(question):
            question.add_view()
            return question

        raise Http404('No question found')

    def get_queryset(self):
        topic = get_object_or_404(Topic, slug=self.kwargs['topic_slug'], site=Site.objects.get_current())

        qs = Question.site_objects.filter(topic=topic)
        if self.request.user.is_anonymous():
            qs = qs.exclude(protected=True)

        return qs


class SubmitFAQ(CreateView):
    model = Question
    form_class = SubmitFAQForm
    template_name = "faq/submit_question.html"
    success_view_name = "faq:faq_submit_thanks"

    def get_form_kwargs(self):
        kwargs = super(SubmitFAQ, self).get_form_kwargs()
        kwargs['instance'] = Question()
        if self.request.user.is_authenticated():
            kwargs['instance'].created_by = self.request.user
        return kwargs

    def form_valid(self, form):
        response = super(SubmitFAQ, self).form_valid(form)
        messages.success(self.request,
            _("Su pregunta fue presentado y será revisada por la inclusión en -Preguntas Frecuentes-."),
            fail_silently=True,
        )
        return response

    def get_success_url(self):
        # The superclass version raises ImproperlyConfigered if self.success_url
        # isn't set. Instead of that, we'll try to redirect to a named view.
        if self.success_url:
            return self.success_url
        else:
            return reverse(self.success_view_name)


class SubmitFAQThanks(TemplateView):
    template_name = "faq/submit_thanks.html"


from django.shortcuts import redirect
from django.contrib import messages


def question_help_full_vote(request, topic_slug, slug):
    if request.GET:
        topic = Topic.site_objects.get(slug=topic_slug)
        question = Question.site_objects.filter(slug=slug, topic=topic)[0]
        data = {}
        user = request.user
        ip_address = request.META.get('HTTP_X_FORWARDED_FOR', '')

        if user.is_authenticated():
            qs_user = user
            qs_done = True if len(QuestionScore.objects.filter(question = question, user = user))>0 else False
        else:
            qs_user = None
            qs_done = True if len(QuestionScore.objects.filter(question = question, ip_address = ip_address, user = None))>0 else False

        # optimistic positive score
        if "n" == request.GET.get("q"):
            qs_score = 0
        else:
            qs_score = 1

        if not qs_done:
            question_score = QuestionScore()
            question_score.question = question
            question_score.user = qs_user
            question_score.score = qs_score
            question_score.ip_address = ip_address
            question_score.save()

            messages.success(request, 'Gracias por ayudarnos, su voto fue registrado.')
        else:
            messages.info(request, 'Ya hemos registrado un voto.')

        return redirect(request.GET.get("redirect"))

class QuestionHelpfulVote(View):

    def post(self, request, topic_slug, slug):
        """
        Scores a question.  The question can only be scored by 0 (not helpful) and 1 (helpful).  A user can score a question
        only once.
         - If the user is logged on we check if he already scored the question
         - If the user is not logged on we check if the ip of the user already scored the question

        :param request:
        :return: a json response
        """
        topic = Topic.site_objects.get(slug=topic_slug)
        question = Question.site_objects.filter(slug=slug, topic=topic)[0]
        data = {}
        user = request.user
        ip_address = request.META.get('HTTP_X_FORWARDED_FOR', '')

        if user.is_authenticated():
            qs_user = user
            qs_done = True if len(QuestionScore.objects.filter(question = question, user = user))>0 else False
        else:
            qs_user = None
            qs_done = True if len(QuestionScore.objects.filter(question = question, ip_address = ip_address, user = None))>0 else False

        # optimistic positive score
        if "n" == request.GET.get("q"):
            qs_score = 0
        else:
            qs_score = 1

        if not qs_done:
            question_score = QuestionScore()
            question_score.question = question

server/compraloahi/templates/faq/base.html
{% extends "layout/base.html" %}
{% block css_header_block %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/less/base.css" >
{% endblock %}
{% block body_block %}

    <div class="container-fluid" style="margin-top: 60px;">
        <div class="row">
            <div class="col-md-12">
                <div class="section">
                    {% for message in messages %}
                        <p class="message">{{ message }}</p>
                    {% endfor %}
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

server/compraloahi/templates/faq/base_list.html
{% extends "layout/base.html" %}
{% block css_header_block %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/less/base.css" >
{% endblock %}
{% block title %}Preguntas frecuentes {% endblock %}
{% block body_block %}

    <div class="page-breadcrumb">
        <ol class="breadcrumb container">
            {% block breadcrumb %}
                <li><a href="/">Inicio</a></li>
                <li><a href="{% url 'faq:faq_index' %}">Preguntas frecuentes</a></li>
            {% endblock %}
        </ol>
    </div>
    <div class="page-title">
        <div class="container">
            <h3>{% block topic_title %}Preguntas frecuentes{% endblock %}</h3>
        </div>
    </div>
    <div id="main-wrapper" class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-white">
                    <div class="panel-body">
                        <h2 class="no-m m-b-lg">¿Como podemos ayudarte?</h2>
                        <form class="m-b-sm" action="/faq/search/">
                            <div class="form-group no-s">
                                <div class="input-group input-group-lg">
                                    <input type="search" class="form-control" value="{{ query }}" name="q" placeholder="Introduzca los términos de búsqueda aquí...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            </div>
                        </form>
                        <a href="/faq/submit/" class="btn btn-success m-b-xs">Hacer nueva pregunta</a>
{#                        <a href="contact.html" class="btn btn-success m-b-xs">Contactanos</a>#}

                        {% block container_list %}
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <a href="/faq/questions/" class="faq-link">
                        <div class="panel panel-green">
                            <div class="panel-body">
                                <h2 class="no-m m-b-md">Todas las preguntas</h2>
                                <p>Lista todas las preguntas..</p>
                            </div>
                        </div>
                    </a>
                {% for topic in topics %}
                    <a href="{{ topic.get_absolute_url }}" class="faq-link">
                        <div class="panel panel-green">
                            <div class="panel-body">
                                <h2 class="no-m m-b-md">{{ topic.name }}</h2>
                                <p>{{ topic.description }}.</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div><!-- Row -->
    </div><!-- Main Wrapper -->

    <div class="cd-overlay"></div>
{% endblock %}

server/compraloahi/templates/faq/index.html
{% extends "faq/base_list.html" %}


{% block topic_title %}Ultimas preguntas{% endblock %}
{% block container_list %}
    <h2 class="m-t-xxl m-b-lg">Ultimas preguntas</h2>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for question in last_updated %}
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne{{ question.id }}">
                    <h4 class="panel-title">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#{{ question.id }}" aria-expanded="false" aria-controls="{{ question.slug }}">
                            {{ question.text }}
                        </a>
                    </h4>
                </div>
                <div id="{{ question.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne{{ question.id }}">
                    <div class="panel-body">
                        <p>{{ question.answer }}</p>
                        <p class="caption"> Fue útil esta pregunta?
                            <span id="feedback-helpful">
                                <a href="/faq/detail/{{ question.topic.slug }}/{{ question.slug }}/helpful/?q=y&redirect={{ request.get_full_path }}" class="feedback-helpful" data="y">Si</a> or
                                <a href="/faq/detail/{{ question.topic.slug }}/{{ question.slug }}/helpful/?q=n&redirect={{ request.get_full_path }}" class="feedback-helpful" data="n">No</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <h2 class="m-t-xxl m-b-lg">Preguntas destacadas</h2>
    <div class="row">
        <div class="col-md-6">
            <ul class="faq-popular list-unstyled">
                {% for question in popular_questions %}
                    <li><a href="#">{{ question.text }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-6">
            <ul class="faq-popular list-unstyled">
                {% for question in popular_questions2 %}
                    <li><a href="#">{{ question.text }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <h2 class="m-t-xxl m-b-lg">Preguntas más frequentes</h2>
    <div class="panel-group" id="accordion2" role="tablist" aria-multiselectable="true">
        {% for question in common_question %}
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne{{ question.slug }}">
                    <h4 class="panel-title">
                        <a class="collapsed" data-toggle="collapse" data-parent="#{{ question.slug }}" href="#{{ question.slug }}" aria-expanded="false" aria-controls="collapseOne">
                            {{ question.text }}
                        </a>
                    </h4>
                </div>
                <div id="{{ question.slug }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne{{ question.slug }}">
                    <div class="panel-body">
                        <p>{{ question.answer }} </p>
                        <p class="caption"> Fue útil esta pregunta?
                            <span id="feedback-helpful">
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=y&redirect={{ request.get_full_path }}" class="feedback-helpful" data="y">Si</a> or
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=n&redirect={{ request.get_full_path }}" class="feedback-helpful" data="n">No</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

















{##}
{##}
{#{% extends "layout/base.html" %}#}
{#{% block css_header_block %}#}
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/less/base.css" >#}
{#{% endblock %}#}
{#{% block body_block %}#}
{##}
{#    <div class="page-breadcrumb">#}
{#        <ol class="breadcrumb container">#}
{#            <li><a href="index.html">Inicio</a></li>#}
{#            <li class="active">Preguntas frecuentes</li>#}
{#        </ol>#}
{#    </div>#}
{#    <div class="page-title">#}
{#        <div class="container">#}
{#            <h3>Preguntas frecuentes</h3>#}
{#        </div>#}
{#    </div>#}
{#    <div id="main-wrapper" class="container">#}
{#        <div class="row">#}
{#            <div class="col-md-9">#}
{#                <div class="panel panel-white">#}
{#                    <div class="panel-body">#}
{#                        <h2 class="no-m m-b-lg">¿Como podemos ayudarte?</h2>#}
{#                        <form class="m-b-sm">#}
{#                            <div class="form-group no-s">#}
{#                                <div class="input-group input-group-lg">#}
{#                                    <input type="search" class="form-control" placeholder="Introduzca los términos de búsqueda aquí...">#}
{#                                    <span class="input-group-btn">#}
{#                                        <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>#}
{#                                    </span>#}
{#                                </div>#}
{#                            </div>#}
{#                        </form>#}
{#                        <a href="/faq/submit/" class="btn btn-success m-b-xs">Hacer nueva pregunta</a>#}
{#                        <a href="contact.html" class="btn btn-success m-b-xs">Contactanos</a>#}
{##}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-3">#}
{#                {% for topic in topics %}#}
{#                    <a href="{{ topic.get_absolute_url }}" class="faq-link">#}
{#                        <div class="panel panel-green">#}
{#                            <div class="panel-body">#}
{#                                <h2 class="no-m m-b-md">{{ topic.name }}</h2>#}
{#                                <p>Vestibulum ante ipsum primis in faucibus orci.</p>#}
{#                            </div>#}
{#                        </div>#}
{#                    </a>#}
{#                {% endfor %}#}
{##}
{#            </div>#}
{#        </div><!-- Row -->#}
{#    </div><!-- Main Wrapper -->#}
{##}
{#    <div class="cd-overlay"></div>#}
{#{% endblock %}#}

server/compraloahi/templates/faq/question_detail.html
{% extends "faq/base.html" %}

{% block title %}{{ block.super }}: Question - {{ question.text|truncatewords:30}}{% endblock %}


{% block body %}

{{ question.text }}

<br/>

{{ question.answer }}

{% endblock %}

server/compraloahi/templates/faq/question_list.html
{% extends "faq/base_list.html" %}

{% block title %}{{ block.super }}: {{ topic }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="active">Todas las preguntas</li>
{% endblock %}

{% block topic_title %}Todas las preguntas{% endblock %}
{% block container_list %}
    <h2 class="m-t-xxl m-b-lg">Preguntas: </h2>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for question in questions %}
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne{{ question.id }}">
                    <h4 class="panel-title">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#{{ question.id }}" aria-expanded="false" aria-controls="{{ question.slug }}">
                            {{ question.text }}
                        </a>
                    </h4>
                </div>
                <div id="{{ question.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne{{ question.id }}">
                    <div class="panel-body">
                        <p>{{ question.answer }}</p>
                        <p>Score : {{ question.score }}</p>
                        <p>Topic : {{ question.topic.name }}</p>
                        <p class="caption"> Fue útil esta pregunta?
                            <span id="feedback-helpful">
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=y&redirect={{ request.get_full_path }}" class="feedback-helpful" data="y">Si</a> or
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=n&redirect={{ request.get_full_path }}" class="feedback-helpful" data="n">No</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

server/compraloahi/templates/faq/search.html
{% extends "faq/base_list.html" %}



{% block title %}{{ block.super }}:  Search - {{ query|truncatewords:30}}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="active">Busqueda/li>
{% endblock %}

{% block topic_title %}Busqueda{% endblock %}
{% block container_list %}
    <h2 class="m-t-xxl m-b-lg">Resultados de busqueda para "{{ query }}" </h2>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        {% for question in questions %}
            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="headingOne{{ question.id }}">
                    <h4 class="panel-title">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#{{ question.id }}" aria-expanded="false" aria-controls="{{ question.slug }}">
                            {{ question.text }}
                        </a>
                    </h4>
                </div>
                <div id="{{ question.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne{{ question.id }}">
                    <div class="panel-body">
                        <p>{{ question.answer }}</p>
                        <p class="caption"> Fue útil esta pregunta?
                            <span id="feedback-helpful">
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=y" class="feedback-helpful" data="y">Si</a> or
                                <a href="/faq/detail/{{ topic.slug }}/{{ question.slug }}/helpful/?q=n" class="feedback-helpful" data="n">No</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

server/compraloahi/templates/faq/submit_question.html
{% extends "faq/base.html" %}
{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans "Signup" %}{% endblock %}

{% block body_block %}
<div class="page-breadcrumb">
        <ol class="breadcrumb container">
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'faq:faq_index' %}">Preguntas frecuentes</a></li>
            <li class="active">Crear pregunta</li>
        </ol>
    </div>
    <div class="page-title">
        <div class="container">
            <h3>Enviar pregunta</h3>
            <p>Usar este formulario para enviar una pregunta (y opcionalmente una respuesta correspondiente ) que le gustaría ver añadido a las preguntas frecuentes sobre este sitio.</p>
        </div>
    </div>
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-6 center">
                    <div class="login-box">
                        <form class="m-t-md" method="post" action="">
                            {% csrf_token %}
                            {% bootstrap_form form %}

                            <button type="submit" class="btn btn-success btn-block m-t-xs">Crear</button>
                        </form>

                    </div>
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->

{% endblock %}

server/compraloahi/templates/faq/submit_thanks.html
{% extends "faq/base.html" %}

{% block title %}{{ block.super }}: Thanks{% endblock %}
{% block body_block %}
    <div class="page-breadcrumb">
        <ol class="breadcrumb container">
            <li><a href="index.html">Inicio</a></li>
            <li class="active"><a href="{% url 'faq:faq_index' %}">Preguntas frecuentes</a></li>
        </ol>
    </div>
    <div id="main-wrapper" class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-white">
                    <div class="panel-body">
                        <h3>Gracias por ayudarnos a crecer!</h3>
                        <p>Con tu ayuda, otras personas se beneficiaran con la informacion.</p>
                        <a href="{% url 'faq:faq_index' %}" class="btn btn-success m-b-xs pull-right">Volver a preguntas frecuentes</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}