server/compraloahi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from apps.favorite.views import HasFavoriteNearApiView

from apps.userProfile.views import StoreView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HomeView, DashBoardView, log, send_notification, TermAndConditionView
from django.views.generic import TemplateView
from django.conf import settings
from apps.util.views import RegisterInterested, TemplateMessage, ContactFormView

urlpatterns = patterns('',
                       url(r'^$', HomeView.as_view()),

    url(r'^report-error/$', 'apps.report_error.views.report_error', name='report-error'),

    url('^interested/$', RegisterInterested.as_view(), name='interested-app'),
    url('^dynamic-message/$', TemplateMessage.as_view(), name='dynamic-message'),
    url(r'^face/$', 'apps.util.views.register_count_whered', {'whered': 'facebook'}),
    url(r'^info/$', 'apps.util.views.register_count_whered', {'whered': 'folleto1'}),
    url(r'^contactenos/$', ContactFormView.as_view(), name='contact'),

    # TODO : This url belong to api
    url(r'^favorites/near/$', HasFavoriteNearApiView.as_view() , name='favorite-near'),

    url(r'^oportunidades-anunciante/$', TemplateView.as_view(template_name='oportunidades-anunciante.html')),

    url(r'^oportunidades-interesado/$', TemplateView.as_view(template_name='oportunidades-interesado.html')),

    url('^faq/', include('apps.faq.urls', namespace='faq')),

    url('^terminosycondiciones/(?P<template>.*)$', TermAndConditionView.as_view(), name='termsandcondition'),

    # Terms and Conditions
    #url(r'^terms/', include('termsandconditions.urls')),

    # Include API
    (r'^api/v1/', include('compraloahi.urls_api', namespace='api')),

    url(r'^favorite/' , include('apps.favorite.urls', namespace='favorite')),

    # URL load dashboard
    url(r'^panel/.*$', DashBoardView.as_view(), name='dashboard'),

    # Admin django
    url(r'^admin/', include(admin.site.urls)),

    # My apps Ad
    url(r'^item/', include("apps.ad.urls", namespace="ad")),

    url(r'^grupos/', include("apps.interest_group.urls", namespace="group")),

    # My apps User
    (r'^users/',
     include('apps.user.urls',
             namespace='my-user')),

    url(r'^calification/', include('apps.rating.urls', namespace="rating")),

    # App Allauth (social authentication)
    (r'^accounts/', include('allauth.urls')),

    # Parche comments
    (r'^comments/post/$',
     'compraloahi.views.comment_post_wrapper'),

    # Package comments
    (r'^comments/', include('django_comments_xtd.urls')),

    url(r'^tienda/(?P<slug>[a-zA-Z0-9_.-]+)/$',
        StoreView.as_view(),
        name="store"),

                       )

if settings.DEBUG:
    urlpatterns =  patterns('',
                      url(r'^send_notification/', send_notification),
                      url(r'^log/', log),
                      url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                      ) + staticfiles_urlpatterns() + urlpatterns

server/apps/comments/models.py
from django_comments_xtd.models import XtdComment

from apps.ad.models import Ad

from django.db.models.signals import post_save
from django.dispatch import receiver
from apps.notification.models import Notification
from django.core.urlresolvers import reverse



@receiver(post_save, sender=XtdComment, dispatch_uid='XTDCommentPostSave')
def handle_xtd_comment_post_save(sender, *args, **kwargs):
    """
        Generate notification when comment on detail ad.
    """
    comment = kwargs['instance']
    if (comment.level == 0 and not kwargs['created']):

        ad = Ad.objects.get(pk=comment.object_pk)
        url = reverse('ad:detail', args=[ad.slug])

        Notification(receiver=ad.author, type='cmmt', message="Nuevo comentario en el aviso " + str(ad.title),
                     extras={"comment": str(comment), "url": url, "ad": comment.object_pk }).save()

server/apps/msg/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext as _
from django.contrib.contenttypes import fields
from django.conf import settings
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver


import datetime
# moderation constants
STATUS_PENDING = 'p'
STATUS_ACCEPTED = 'a'
STATUS_REJECTED = 'r'
STATUS_CHOICES = (
    (STATUS_PENDING, _('Pending')),
    (STATUS_ACCEPTED, _('Accepted')),
    (STATUS_REJECTED, _('Rejected')),)


from django.contrib.contenttypes.models import ContentType
# related_objec_type = ContentType.objects.get(app_label=settings.MSG_RELATED_APP_LABEL, model=settings.MSG_RELATED_MODEL)

class Msg(models.Model):
    """
    A message between a User and another User or an AnonymousUser.
    """
    SUBJECT_MAX_LENGTH = 120

    TRUE_VALUES = set(('t', 'T', 'true', 'True', 'TRUE', '1', 1, True))
    FALSE_VALUES = set(('f', 'F', 'false', 'False', 'FALSE', '0', 0, 0.0, False))

    subject = models.CharField(_("subject"), max_length=30)
    body = models.TextField(_("body"), blank=True)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,
        related_name='msg_sent_messages', null=True, blank=True,
        verbose_name=_("sender"))
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL,
        related_name='msg_received_messages', null=True, blank=True,
        verbose_name=_("recipient"))
    parent = models.ForeignKey('self', related_name='msg_next_messages', null=True, blank=True, verbose_name=_("parent message"))
    thread = models.ForeignKey('self', related_name='msg_child_messages', null=True, blank=True, verbose_name=_("root message"))
    sent_at = models.DateTimeField(_("sent at"), auto_now_add=True)
    read_at = models.DateTimeField(_("read at"), null=True, blank=True)
    replied_at = models.DateTimeField(_("replied at"), null=True, blank=True)
    sender_archived = models.BooleanField(_("archived by sender"), default=False)
    recipient_archived = models.BooleanField(_("archived by recipient"), default=False)
    sender_deleted_at = models.DateTimeField(_("deleted by sender at"), null=True, blank=True)
    recipient_deleted_at = models.DateTimeField(_("deleted by recipient at"), null=True, blank=True)
    # moderation fields
    moderation_status = models.CharField(_("status"), max_length=1, choices=STATUS_CHOICES, default=STATUS_PENDING)
    # moderation_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='moderated_messages',
    #     null=True, blank=True, verbose_name=_("moderator"))
    moderation_date = models.DateTimeField(_("moderated at"), null=True, blank=True)
    moderation_reason = models.CharField(_("rejection reason"), max_length=120, blank=True)
    # related_obj = generic.GenericForeignKey(related_objec_type, settings.MSG_RELATED_OBJ_ID)
    # related_obj_type = ContentType.objects.get(app_label="apps.ad", model="Ad")
    # related_obj = generic.GenericForeignKey(related_obj_type, 'pk')
    # objects = MessageManager()
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    related_obj = fields.GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = _("message")
        verbose_name_plural = _("messages")
        ordering = ['-sent_at', '-id']

    def is_pending(self):
        """Tell if the message is in the pending state."""
        return self.moderation_status == STATUS_PENDING
    def is_rejected(self):
        """Tell if the message is in the rejected state."""
        return self.moderation_status == STATUS_REJECTED
    def is_accepted(self):
        """Tell if the message is in the accepted state."""
        return self.moderation_status == STATUS_ACCEPTED

    @property
    def is_new(self):
        """Tell if the recipient has not yet read the message."""
        return self.read_at is None
        # return True

    @is_new.setter
    def is_new(self, value):
        if not self.read_at and value in self.FALSE_VALUES:
            self.read_at = datetime.datetime.now()
            self.save()
        elif value in self.TRUE_VALUES:
            self.read_at = None
            self.save()


    @property
    def is_replied(self):
        """Tell if the recipient has written a reply to the message."""
        return self.replied_at is not None

    @is_replied.setter
    def is_replied(self, value):
        if not self.replied_at and value in self.TRUE_VALUES:
            self.replied_at = datetime.datetime.now()
            self.save()
        elif value in self.FALSE_VALUES:
            self.replied_at = None
            self.save()

    @property
    def sender_deleted(self):
        """Tell if the recipient has written a reply to the message."""
        return self.sender_deleted_at is not None

    @sender_deleted.setter
    def sender_deleted(self, value):
        if not self.sender_deleted_at and value in self.TRUE_VALUES:
            self.sender_deleted_at = datetime.datetime.now()
            self.save()
        elif value in self.FALSE_VALUES:
            self.sender_deleted_at = None
            self.save()

    @property
    def recipient_deleted(self):
        """Tell if the recipient has written a reply to the message."""
        return self.recipient_deleted_at is not None

    @recipient_deleted.setter
    def recipient_deleted(self, value):
        if not self.recipient_deleted and value in self.TRUE_VALUES:
            self.recipient_deleted_at = datetime.datetime.now()
            self.save()
        elif value in self.FALSE_VALUES:
            self.recipient_deleted_at = None
            self.save()


@receiver(post_save, sender=Msg)
def msg_check_thread_post_save(sender, *args, **kwargs):
    if kwargs['created']:
        msg = kwargs['instance']
        # TODO: This resolve problem with get the last message by thread on inbox.
        if not msg.thread:
            msg.thread = msg
            msg.save()

server/apps/comments/views.py
import datetime

from django.db.models import F

from django_comments_xtd.models import XtdComment

from django_filters import FilterSet, MethodFilter

from rest_framework import viewsets, filters
from rest_framework.decorators import list_route

from apps.ad.models import Ad

from .serializers import XtdCommentSerializer


class XtdCommentFilter(FilterSet):
    id_not = MethodFilter(action='filter_id')
    class Meta:
        model = XtdComment
        fields = ['object_pk', 'user', 'parent_id', 'id_not']

    def filter_id(self, queryset, value):
        return queryset.exclude(pk=value)


class ThreadedCommentViewSet(viewsets.ModelViewSet):
    queryset = XtdComment.objects.all()
    serializer_class = XtdCommentSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = XtdCommentFilter

    def perform_create(self, serializer):
        content_object = Ad.objects.get(pk=self.request.data.get('object_pk', 0))
        if self.request.user.is_authenticated():
            serializer.save(user=self.request.user,
                            content_object=content_object,
                            submit_date=datetime.datetime.today(),
                            site_id=1)
        return super(ThreadedCommentViewSet, self).perform_create(serializer)

    @list_route(methods=['get'])
    def last(self, request, *args, **kwargs):
        self.queryset = self.get_queryset().filter(pk=F('parent_id'))
        return super(ThreadedCommentViewSet,self).list(request, *args, **kwargs)

server/compraloahi/views.py
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django_comments.views.comments import post_comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User

from rest_framework import pagination

from push_notifications.models import GCMDevice
from django.views.decorators.csrf import csrf_exempt

from apps.ad.models import Ad
from apps.user.serializers import UserAuthenticationSerializer
from apps.util.forms import RegisterInterestedForm


import logging

logger = logging.getLogger('debug')

@csrf_exempt
def log(request):
    logger.debug( request.body )
    return HttpResponse( "algo" )


# Test send notification to android
def send_notification(request):
    device = GCMDevice.objects.first()

    device.send_message(request.GET.get('msg', "Hola"))

    return HttpResponse("Notificacion enviada con exito")


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        cxt = super(HomeView, self).get_context_data(*args, **kwargs)
        cxt['form'] = RegisterInterestedForm()
        return cxt

    #def dispatch(self, request, *args, **kwargs):
    #    return redirect('/item/search/?q=')

class TermAndConditionView(TemplateView):
    template_name = 'termcondition/index.html'

    def get_template_names(self):
        if self.kwargs.get('template'):
            return 'termcondition/%s.html' %(self.kwargs['template'])
        else:
            return super(TermAndConditionView, self).get_template_names()

class DashBoardView(TemplateView):
    """
        View to init dashboard
    """
    template_name = 'dashboard/base.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DashBoardView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DashBoardView, self).get_context_data(**kwargs)

        context['user_data'] = UserAuthenticationSerializer(instance=self.request.user).data
        return context


def comment_post_wrapper(request):
    if request.user.is_authenticated():
        # In case of a reply, check that the user is answering a comment of his own ad
        object_pk = request.POST.get('object_pk', '')
        if int( request.POST.get('reply_to', 0) ) > 0:
            if ( Ad.objects.get(pk=object_pk).author == request.user):
                return post_comment(request) # VER SI ESTE ES EL POST, o EL DE COMMENT XTD
        else:
            if ( Ad.objects.get(pk=object_pk).author != request.user):
                return post_comment(request) # VER SI ESTE ES EL POST, o EL DE COMMENT XTD

    return HttpResponse('Unauthorized', status=401)


# Generates Auth Tokens for all Users
class GenerateAllAuthToken(APIView):
    def get(self, request):
        response = "{"
        for user in User.objects.all():
            token, created = Token.objects.get_or_create(user=user)
            response += "{" + "username:" + user.username + ",pk: " + str(user.pk) + ",token:" + token.key + "},"
        response += "}"
        return Response(response)

generate_all_auth_token = GenerateAllAuthToken.as_view()


class CustomPagination(pagination.PageNumberPagination):
    page_size = 200
    page_size_query_param = 'page'
    max_page_size = 200
    """
        Custom pagination
            return only page number in next and previous pages.
    """
    def get_paginated_response(self, data):
        resp = {}
        resp['next'] = self.page.next_page_number() if self.page.has_next() else None
        resp['previous'] = self.page.previous_page_number() if self.page.has_previous() else None
        resp['count'] = self.page.paginator.count
        resp['results'] = data
        return Response(resp)

server/compraloahi/templates/comments/base.html
{% extends "base.html" %}{% load i18n %}

{% block headtitle %}{% block title %}{% trans "Responses for page" %}{% endblock %}{% endblock %}

{% block main %}
    <div id="comments-wrapper">
        {% block content %}{% endblock %}
    </div>
{% endblock %}

server/compraloahi/templates/comments/form.html
{% load comments i18n %}
{% load common_tags %}


<form class="form-horizontal" id="frm-post-comment" action="{% comment_form_target %}" method="post">{% csrf_token %}
    <fieldset>
        {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
        {% for field in form %}
            {% if field.is_hidden %}
                <div>{{ field }}</div>
            {% else %}
                {% if field.errors %}{{ field.errors }}{% endif %}

                <p {% if field.errors %} class="error"{% endif %}>
                    <!-- TODO: This is a bad way of hidding unnecesary fields -->
                    {% if field.name == "comment" %}
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea class="form-control" cols="40" id="id_{{ field.name }}" maxlength="3000" name="{{ field.name }}" placeholder="Deja tu comentario.." rows="10"></textarea>
                            </div>
                        </div>
                    {% endif %}
                </p>
            {% endif %}
        {% endfor %}

        <!-- Message body -->
        <!--
          <div class="form-group">
            <div class="col-md-12">
              <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
            </div>
          </div>
          -->

        <!-- Form actions -->
        <div class="form-group">
            <div class="col-md-12 text-right">
                <button type="button" id="btn-post-comment" name="post" class="btn btn-md" >Enviar</button>
            </div>
        </div>
    </fieldset>
</form>


<div class="modal" id="modalMsg">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">AVISO :</h4>
            </div>
            <div class="modal-body" id="content">

            </div>
            <div class="modal-footer">
                <button type="button" class="close btn btn-success" data-dismiss="modal" aria-hidden="true">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    //Submit form ajax
    //Parameter Object to container search component
    function submit_comment_ajax(container_to_search){

        container_to_search.find('#btn-post-comment').click(function() {
            // Script Post Comment Ajax
            var obj = {};

            obj.reply_to = container_to_search.find("#frm-post-comment").find("#id_reply_to").val();

            obj.csrfmiddlewaretoken = container_to_search.find("#frm-post-comment").find("input[name='csrfmiddlewaretoken']").val();
            obj.content_type = container_to_search.find("#frm-post-comment").find("#id_content_type").val();
            obj.object_pk = container_to_search.find("#frm-post-comment").find("#id_object_pk").val();
            obj.timestamp = container_to_search.find("#frm-post-comment").find("#id_timestamp").val();
            obj.security_hash = container_to_search.find("#frm-post-comment").find("#id_security_hash").val();
            obj.comment = container_to_search.find("#frm-post-comment").find("#id_comment").val();

            obj.post = "Post";

            if(obj.comment != ""){

                $.ajax({
                    url: "/comments/post/",
                    type: 'POST',
                    beforeSend: function(xhr, settings){
                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    },
                    data: obj,
                    success: function(data) {
                        container_to_search.find("#frm-post-comment").find("#id_comment").val("");
                            //var msg = "<p>El comentario se creo correctamente, en breve sera publicado</p>";
                            //$("#form-comment-list").
                            //        $('#modalMsg').find("#content").html(msg);
                            //$('#modalMsg').modal('show');
                            toastr.success('El comentario se creo correctamente, en breve sera publicado');

                            if(container_to_search.attr("id") == 'modalReplyComment'){
                                container_to_search.modal('hide');
                            }
                    },
                    error: function(data){
                        toastr.error('Error al publicar el comentario, vuelva a intentarlo mas tarde');
                    }
                });


            }else{
                 container_to_search.find("#frm-post-comment").append(alert("Es necesario dejar un comentario antes de enviarlo.", 'danger'));
            }
        });
    }
</script>

server/compraloahi/templates/comments/list.html
{% load i18n comments_xtd %}
{% load common_tags %}



<div class="panel panel-default widget">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-comment"></span>
        Preguntas
        <sup class="label label-info">
            {{ comment_count }}</sup>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            {% for comment in comment_list|slice0to:comments_limit %}
                <li class="list-group-item" >
                    <div class="row" style="margin-left:{{ comment.level }}00px;">
                        <div>
                            {{ comment.submit_date }}&nbsp;-&nbsp;
                            {% if comment.url %}<a href="{{ comment.url }}" target="_new">{% endif %}{{ comment.name }}{% if comment.url %}</a>{% endif %}{% if comment.allow_thread %}&nbsp;-&nbsp;
                                 {% if item.author == user and comment.user.id != user.id %}
                                    <!-- BUTTON REPLY -->
                                <button data-toggle="modal" class="btn btn-xs btn-success btn-reply-comment" data-target="#modalReplyComment" data-comment-id="{{ comment.id }}">
                                    Contestar
                                </button>
                                {% endif %}
                            {% endif %}

                        </div>
                        <div class="comment-text">
                            {{ comment.comment|render_markup_comment }}
                        </div>
                        <!--
                        <div class="action">
                            <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                            <button type="button" class="btn btn-success btn-xs" title="Approved">
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                            <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </div>
                        -->
                    </div>
                </li>
            {% endfor %}
    </ul>
        {% if comment_list|length > comments_limit %}
        <a id="more-comments-btn" class="btn btn-primary btn-sm btn-block" role="button"
               href="/item/{{ object.slug }}/?comments_limit={{ comments_limit|add:5 }}">
            <span class="glyphicon glyphicon-refresh"></span> More</a>
        {% endif %}
</div>
</div>





<!-- MODAL REPLY COMMENT -->
<div class="modal" id="modalReplyComment">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Reply Comment</h4>
            </div>
            <div class="modal-body" id="content">

            </div>
        </div>
    </div>
</div>


<script>
    // Script Reply Comment Ajax

    // Add event to reply buttons
    $('.btn-reply-comment').click(function() {

        var comment_id_to_reply = $(this).data('comment-id');

        // Get form to reply
        $.get("/comments/reply/" + comment_id_to_reply,
                function(data){
                    //var span_id_comment = "<span hidden='True' data-comment-id='" + comment_id_to_reply + "' id='comment-id-reply'></span>";
                    var modal_container_reply = $("#modalReplyComment");
                    modal_container_reply.find("#content").html(data);
                    submit_comment_ajax(modal_container_reply);
                    //$("#modalReplyComment").find("#content").html(span_id_comment);
                });
    });
</script>

server/compraloahi/templates/comments/posted.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Comment confirmation requested" %}.{% endblock %}

{% block content %}
  <h1>{% trans "Comment confirmation requested" %}</h1>
  <p>{% trans "A confirmation message has been sent to your email address. Please, click on the link in the message to confirm your comment." %}</p>
{% endblock %}

server/compraloahi/templates/comments/preview.html
{% extends "comments/base.html" %}
{% load i18n %}

{% block title %}{% trans "Preview your comment" %}{% endblock %}

{% block content %}
  {% load comments %}
  <form action="{% comment_form_target %}" method="post">{% csrf_token %}
    {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
    {% if form.errors %}
    <h1>{% if form.errors|length == 1 %}{% trans "Please correct the error below" %}{% else %}{% trans "Please correct the errors below" %}{% endif %}</h1>
    {% else %}
    <h1>{% trans "Preview your comment" %}</h1>
      <blockquote>{{ comment|linebreaks }}</blockquote>
      <p>
      {% trans "and" %} <input type="submit" name="submit" class="submit-post" value="{% trans "Post your comment" %}" id="submit" /> {% trans "or make changes" %}:
      </p>
    {% endif %}
    {% for field in form %}
      {% if field.is_hidden %}
        <div>{{ field }}</div>
      {% else %}
        {% if field.errors %}{{ field.errors }}{% endif %}
        <p
          {% if field.errors %} class="error"{% endif %}
          {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
          {{ field.label_tag }} {{ field }}
        </p>
      {% endif %}
    {% endfor %}
    <p class="submit">
    <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
    <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </form>
{% endblock %}